version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: go-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 51177477
      POSTGRES_DB: testdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-app
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 51177477
      DB_NAME: testdb
    ports:
      - "8000:8080"
    depends_on:
      - db
    volumes:
      - ../internal/db/migrations:/app/internal/db/migrations

volumes:
  pgdata: