version: '3.8'

services:
  postgres:
    image: postgres:17.4-alpine
    container_name: go-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 51177477
      POSTGRES_DB: postgres
    ports:
      - "5442:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  go-app:
    build: .
    ports:
      - "8088:8080"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:51177477@postgres:5432/postgres?sslmode=disable

volumes:
  postgres_data:
